a = "today is a wonderful day"
print('@'.join(a))
print(a.find('day',6))
print(a.index("day",5))
print(a.replace('a','@s'))
print(a.count("day"))
print(a.isalpha())
print(a.isupper())
print(a.swapcase())
print(a.split())
print(a.partition('o'))
print(a.endswith('day'))
print(id(5.0))
print('H' in 'Hurray')
print(ord('A'))
print(chr(65))
print('-'.join('12345'))
